USE BetterLinkedIn_sp20; 

-- List of industries from: https://github.com/dariusk/corpora/blob/master/data/corporations/industries.json
INSERT INTO Industries (IndustryName) VALUE ("Accounting");
INSERT INTO Industries (IndustryName) VALUE ("Airlines & Aviation");
INSERT INTO Industries (IndustryName) VALUE ("Alternative Dispute Resolution");
INSERT INTO Industries (IndustryName) VALUE ("Alternative Medicine");
INSERT INTO Industries (IndustryName) VALUE ("Animation");
INSERT INTO Industries (IndustryName) VALUE ("Apparel & Fashion");
INSERT INTO Industries (IndustryName) VALUE ("Architecture & Planning");
INSERT INTO Industries (IndustryName) VALUE ("Arts & Crafts");
INSERT INTO Industries (IndustryName) VALUE ("Automotive");
INSERT INTO Industries (IndustryName) VALUE ("Aviation & Aerospace");
INSERT INTO Industries (IndustryName) VALUE ("Banking");
INSERT INTO Industries (IndustryName) VALUE ("Biotechnology");
INSERT INTO Industries (IndustryName) VALUE ("Broadcast Media");
INSERT INTO Industries (IndustryName) VALUE ("Building Materials");
INSERT INTO Industries (IndustryName) VALUE ("Business Supplies & Equipment");
INSERT INTO Industries (IndustryName) VALUE ("Capital Markets");
INSERT INTO Industries (IndustryName) VALUE ("Chemicals");
INSERT INTO Industries (IndustryName) VALUE ("Civic & Social Organization");
INSERT INTO Industries (IndustryName) VALUE ("Civil Engineering");
INSERT INTO Industries (IndustryName) VALUE ("Commercial Real Estate");
INSERT INTO Industries (IndustryName) VALUE ("Computer & Network Security");
INSERT INTO Industries (IndustryName) VALUE ("Computer Games");
INSERT INTO Industries (IndustryName) VALUE ("Computer Hardware");
INSERT INTO Industries (IndustryName) VALUE ("Computer Networking");
INSERT INTO Industries (IndustryName) VALUE ("Computer Software");
INSERT INTO Industries (IndustryName) VALUE ("Construction");
INSERT INTO Industries (IndustryName) VALUE ("Consumer Electronics");
INSERT INTO Industries (IndustryName) VALUE ("Consumer Goods");
INSERT INTO Industries (IndustryName) VALUE ("Consumer Services");
INSERT INTO Industries (IndustryName) VALUE ("Cosmetics");
INSERT INTO Industries (IndustryName) VALUE ("Dairy");
INSERT INTO Industries (IndustryName) VALUE ("Defense & Space");
INSERT INTO Industries (IndustryName) VALUE ("Design");
INSERT INTO Industries (IndustryName) VALUE ("Education Management");
INSERT INTO Industries (IndustryName) VALUE ("E learning");
INSERT INTO Industries (IndustryName) VALUE ("Electrical & Electronic Manufacturing");
INSERT INTO Industries (IndustryName) VALUE ("Entertainment");
INSERT INTO Industries (IndustryName) VALUE ("Environmental Services");
INSERT INTO Industries (IndustryName) VALUE ("Events Services");
INSERT INTO Industries (IndustryName) VALUE ("Executive Office");
INSERT INTO Industries (IndustryName) VALUE ("Facilities Services");
INSERT INTO Industries (IndustryName) VALUE ("Farming");
INSERT INTO Industries (IndustryName) VALUE ("Financial Services");
INSERT INTO Industries (IndustryName) VALUE ("Fine Art");
INSERT INTO Industries (IndustryName) VALUE ("Fishery");
INSERT INTO Industries (IndustryName) VALUE ("Food & Beverages");
INSERT INTO Industries (IndustryName) VALUE ("Food Production");
INSERT INTO Industries (IndustryName) VALUE ("Fundraising");
INSERT INTO Industries (IndustryName) VALUE ("Furniture");
INSERT INTO Industries (IndustryName) VALUE ("Gambling & Casinos");
INSERT INTO Industries (IndustryName) VALUE ("Glass & Ceramics & Concrete");
INSERT INTO Industries (IndustryName) VALUE ("Government Administration");
INSERT INTO Industries (IndustryName) VALUE ("Government Relations");
INSERT INTO Industries (IndustryName) VALUE ("Graphic Design");
INSERT INTO Industries (IndustryName) VALUE ("Health & Wellness & Fitness");
INSERT INTO Industries (IndustryName) VALUE ("Higher Education");
INSERT INTO Industries (IndustryName) VALUE ("Hospital & Health Care");
INSERT INTO Industries (IndustryName) VALUE ("Hospitality");
INSERT INTO Industries (IndustryName) VALUE ("Human Resources");
INSERT INTO Industries (IndustryName) VALUE ("Import & Export");
INSERT INTO Industries (IndustryName) VALUE ("Individual & Family Services");
INSERT INTO Industries (IndustryName) VALUE ("Industrial Automation");
INSERT INTO Industries (IndustryName) VALUE ("Information Services");
INSERT INTO Industries (IndustryName) VALUE ("Information Technology & Services");
INSERT INTO Industries (IndustryName) VALUE ("Insurance");
INSERT INTO Industries (IndustryName) VALUE ("International Affairs");
INSERT INTO Industries (IndustryName) VALUE ("International Trade & Development");
INSERT INTO Industries (IndustryName) VALUE ("Internet");
INSERT INTO Industries (IndustryName) VALUE ("Investment Banking & Venture");
INSERT INTO Industries (IndustryName) VALUE ("Investment Management");
INSERT INTO Industries (IndustryName) VALUE ("Judiciary");
INSERT INTO Industries (IndustryName) VALUE ("Law Enforcement");
INSERT INTO Industries (IndustryName) VALUE ("Law Practice");
INSERT INTO Industries (IndustryName) VALUE ("Legal Services");
INSERT INTO Industries (IndustryName) VALUE ("Legislative Office");
INSERT INTO Industries (IndustryName) VALUE ("Leisure & Travel");
INSERT INTO Industries (IndustryName) VALUE ("Libraries");
INSERT INTO Industries (IndustryName) VALUE ("Logistics & Supply Chain");
INSERT INTO Industries (IndustryName) VALUE ("Luxury Goods & Jewelry");
INSERT INTO Industries (IndustryName) VALUE ("Machinery");
INSERT INTO Industries (IndustryName) VALUE ("Management Consulting");
INSERT INTO Industries (IndustryName) VALUE ("Maritime");
INSERT INTO Industries (IndustryName) VALUE ("Marketing & Advertising");
INSERT INTO Industries (IndustryName) VALUE ("Market Research");
INSERT INTO Industries (IndustryName) VALUE ("Mechanical or Industrial Engineering");
INSERT INTO Industries (IndustryName) VALUE ("Media Production");
INSERT INTO Industries (IndustryName) VALUE ("Medical Device");
INSERT INTO Industries (IndustryName) VALUE ("Medical Practice");
INSERT INTO Industries (IndustryName) VALUE ("Mental Health Care");
INSERT INTO Industries (IndustryName) VALUE ("Military");
INSERT INTO Industries (IndustryName) VALUE ("Mining & Metals");
INSERT INTO Industries (IndustryName) VALUE ("Motion Pictures & Film");
INSERT INTO Industries (IndustryName) VALUE ("Museums & Institutions");
INSERT INTO Industries (IndustryName) VALUE ("Music");
INSERT INTO Industries (IndustryName) VALUE ("Nanotechnology");
INSERT INTO Industries (IndustryName) VALUE ("Newspapers");
INSERT INTO Industries (IndustryName) VALUE ("Nonprofit Organization Management");
INSERT INTO Industries (IndustryName) VALUE ("Oil & Energy");
INSERT INTO Industries (IndustryName) VALUE ("Online Publishing");
INSERT INTO Industries (IndustryName) VALUE ("Outsourcing & Offshoring");
INSERT INTO Industries (IndustryName) VALUE ("Package & Freight Delivery");
INSERT INTO Industries (IndustryName) VALUE ("Packaging & Containers");
INSERT INTO Industries (IndustryName) VALUE ("Paper & Forest Products");
INSERT INTO Industries (IndustryName) VALUE ("Performing Arts");
INSERT INTO Industries (IndustryName) VALUE ("Pharmaceuticals");
INSERT INTO Industries (IndustryName) VALUE ("Philanthropy");
INSERT INTO Industries (IndustryName) VALUE ("Photography");
INSERT INTO Industries (IndustryName) VALUE ("Plastics");
INSERT INTO Industries (IndustryName) VALUE ("Political Organization");
INSERT INTO Industries (IndustryName) VALUE ("Primary & Secondary");
INSERT INTO Industries (IndustryName) VALUE ("Printing");
INSERT INTO Industries (IndustryName) VALUE ("Professional Training");
INSERT INTO Industries (IndustryName) VALUE ("Program Development");
INSERT INTO Industries (IndustryName) VALUE ("Public Policy");
INSERT INTO Industries (IndustryName) VALUE ("Public Relations");
INSERT INTO Industries (IndustryName) VALUE ("Public Safety");
INSERT INTO Industries (IndustryName) VALUE ("Publishing");
INSERT INTO Industries (IndustryName) VALUE ("Railroad Manufacture");
INSERT INTO Industries (IndustryName) VALUE ("Ranching");
INSERT INTO Industries (IndustryName) VALUE ("Real Estate");
INSERT INTO Industries (IndustryName) VALUE ("Recreational");
INSERT INTO Industries (IndustryName) VALUE ("Religious Institutions");
INSERT INTO Industries (IndustryName) VALUE ("Renewables & Environment");
INSERT INTO Industries (IndustryName) VALUE ("Research");
INSERT INTO Industries (IndustryName) VALUE ("Restaurants");
INSERT INTO Industries (IndustryName) VALUE ("Retail");
INSERT INTO Industries (IndustryName) VALUE ("Security & Investigations");
INSERT INTO Industries (IndustryName) VALUE ("Semiconductors");
INSERT INTO Industries (IndustryName) VALUE ("Shipbuilding");
INSERT INTO Industries (IndustryName) VALUE ("Sporting Goods");
INSERT INTO Industries (IndustryName) VALUE ("Sports");
INSERT INTO Industries (IndustryName) VALUE ("Staffing & Recruiting");
INSERT INTO Industries (IndustryName) VALUE ("Supermarkets");
INSERT INTO Industries (IndustryName) VALUE ("Telecommunications");
INSERT INTO Industries (IndustryName) VALUE ("Textiles");
INSERT INTO Industries (IndustryName) VALUE ("Think Tanks");
INSERT INTO Industries (IndustryName) VALUE ("Tobacco");
INSERT INTO Industries (IndustryName) VALUE ("Translation & Localization");
INSERT INTO Industries (IndustryName) VALUE ("Transportation & Trucking & Railroad");
INSERT INTO Industries (IndustryName) VALUE ("Utilities");
INSERT INTO Industries (IndustryName) VALUE ("Venture Capital");
INSERT INTO Industries (IndustryName) VALUE ("Veterinary");
INSERT INTO Industries (IndustryName) VALUE ("Warehousing");
INSERT INTO Industries (IndustryName) VALUE ("Wholesale");
INSERT INTO Industries (IndustryName) VALUE ("Wine & Spirits");
INSERT INTO Industries (IndustryName) VALUE ("Wireless");
INSERT INTO Industries (IndustryName) VALUE ("Writing & Editing");
